[package]
name = "exofetch-rs"
version = "0.1.0"
authors = ["Vin√≠cius R. Miguel <36349314+vrmiguel@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs      = "2.0.2"

[dependencies.whoami]
path = "whoami"